services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.24.1
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - ./docker/neo4j/conf:/conf
      - ./docker/neo4j/import:/import
      - ./docker/neo4j/script:/script
    environment:
      - NEO4J_AUTH=neo4j/$NEO4J_ROOT_PASSWORD
      - NEO4J_dbms_default__database=$NEO4J_DATABASE
      - EXTENSION_SCRIPT=/script/import_csv.sh

volumes:
  neo4j-data:
  neo4j-logs: